switch("path", "$projectDir/../../src")
switch("threads", "on")
switch("mm", "orc")
switch("define", "concurrent.smartptrs.leakCheck")
switch("define", "useMalloc")
switch("passC", "-fsanitize=leak")
switch("passL", "-fsanitize=leak")
switch("debugger", "native")
