name: docs
on:
  push:
    branches:
      - main
env:
  deploy-dir: .gh-pages
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - run: |
          wget -O /tmp/choosenim-init.sh https://nim-lang.org/choosenim/init.sh
          sh /tmp/choosenim-init.sh -y
          echo ~/.nimble/bin >> $GITHUB_PATH
          ~/.nimble/bin/choosenim devel

      - run: nimble install -y
      - run: nimble doc --index:on --project --git.url:https://github.com/${{ github.repository }} --git.commit:main  --out:${{ env.deploy-dir }} ${{ env.nim-src }}
      - name: "Copy to index.html"
        run: cp ${{ env.deploy-dir }}/${{ github.event.repository.name }}.html ${{ env.deploy-dir }}/index.html
      - name: Deploy documents
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.deploy-dir }}
