name: Test
on:
  push:
    branches:
    - main
    - devel
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        nim-version: [devel]
        backend: [c]

    runs-on: ubuntu-latest

    container:
      image: ros:humble-ros-base

    steps:
    - run: |
        apt-get update -y
        apt-get install -y wget gcc ros-humble-rcl ros-humble-builtin-interfaces ros-humble-std-srvs
        wget -O /tmp/choosenim-init.sh https://nim-lang.org/choosenim/init.sh
        sh /tmp/choosenim-init.sh -y
        echo ~/.nimble/bin >> $GITHUB_PATH
        ~/.nimble/bin/choosenim ${{ matrix.nim-version }}

    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - run: git config --global --add safe.directory /__w/rclnim/rclnim
    - run: nimble install -y --verbose
    - run: source /opt/ros/humble/setup.bash && nimble test${{ matrix.backend }}
      shell: bash
